version: '3.5'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: databaseuser
      POSTGRES_PASSWORD: databasepassword
      POSTGRES_DB: rinhabackendpg
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'

  api1: &api
    build: .
    hostname: api1
    image: cedraz/rinha-de-backend-api:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"
    environment:
      DATABASE_URL: "postgresql://databaseuser:databasepassword@db:5432/rinhabackendpg?schema=public"

  api2:
    <<: *api
    ports:
      - "8082:8080"
    hostname: api2

  nginx:
    image: nginx:latest
    volumes:
      - ./.config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
